version: '3.7'
services:

    tcapi:
        container_name: tcapi
        build: ./tcapi/.
        volumes:
            - ./tcapi:/usr/local/mount
        ports:
          - "8000:8000"
        environment:
            LISTEN_ADDRESS: ":8000"
            REDIS_ADDRESS: "redis:6379"
            REDIS_PASSWORD: ""
            REDIS_DB: "0"

    protos:
        container_name: protos
        build: ./protos/.
        volumes:
            - ./protos/:/usr/local/mount
        environment:
            MOUNT_DIR: /usr/local/mount

    testtcapi:
        container_name: testtcapi
        build: ./testtcapi/.
        volumes:
            - ./testtcapi/:/usr/local/mount
        environment:
            STUB_ADDRESS: "tcapi:8000"
            SLEEP: "0"
            # SLEEP: "999999"
            MOUNT_DIR: /usr/local/mount

    redis:
        container_name: redis
        image: 'bitnami/redis:latest'
        ports:
          - "6379:6379"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        # volumes:
        #   - '/path/to/redis-persistence:/bitnami'

    sharedb:
        container_name: sharedb
        build: ./sharedb/.
        volumes:
            - ./sharedb/:/usr/local/mount
        ports:
          - "8080:8080"
        environment:
            SLEEP: "0"
            # SLEEP: "999999"

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: local
            MONGO_INITDB_ROOT_PASSWORD: local
