version: '3.7'
services:

    tcapi:
        container_name: tcapi
        build: ./tcapi/.
        volumes:
            - ./tcapi:/usr/local/mount
        ports:
          - "8000:8000"
        environment:
            LISTEN_ADDRESS: ":8000"

    protos:
        container_name: protos
        build: ./protos/.
        volumes:
            - ./protos/:/usr/local/mount

    # jstests:
    #     container_name: jstests
    #     build: ./jstests/.
    #     environment:
    #         HOSTNAME: tcapi
    #         PORT: "8000"
