version: '3.7'
services:

    tcapi:
        container_name: tcapi
        build: ./tcapi/.
        volumes:
            - ./tcapi:/usr/local/mount
        ports:
          - "8000:8000"
        environment:
            LISTEN_ADDRESS: ":8000"

    protos:
        container_name: protos
        build: ./protos/.
        volumes:
            - ./protos/:/usr/local/mount
        environment:
            MOUNT_DIR: /usr/local/mount

    testtcapi:
        container_name: testtcapi
        build: ./testtcapi/.
        environment:
            DIAL_TARGET: "tcapi:8000"
            SLEEP: "999999"
            # SLEEP: "0"
