# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcapi.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tcapi.proto", :syntax => :proto3) do
    add_message "app.Document" do
      optional :uuid, :string, 1
      optional :name, :string, 2
    end
    add_message "app.DocumentQuery" do
      optional :page, :int64, 1
      optional :size, :int64, 2
    end
    add_message "app.DocumentList" do
      repeated :documents, :message, 1, "app.Document"
    end
    add_message "app.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "app.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module App
  Document = Google::Protobuf::DescriptorPool.generated_pool.lookup("app.Document").msgclass
  DocumentQuery = Google::Protobuf::DescriptorPool.generated_pool.lookup("app.DocumentQuery").msgclass
  DocumentList = Google::Protobuf::DescriptorPool.generated_pool.lookup("app.DocumentList").msgclass
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("app.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("app.HelloReply").msgclass
end
